### ISSUE TITLE
License for SecureBoot Context

### ISSUE THREAD

**Issue by embetrix** [usbarmory/caam-keyblob#6]
Hi,

the GPLv3 licensing is inappropriate in using  it with SecureBoot Context.

would be it possible to relicense in GPLv2 ?

Thank you

**Comment by abarisani** [comment]
The CAAM keyblob functionality is not required for secure boot functionality. Secure Boot uses HAB and entails authentication, not symmetric encryption.

Also the GPLv3 restriction applies in specific use cases that lock the user out.

If you really think the CAAM keyblob driver needs to be used in scenarios compatible with "tivoization" clause please contact me directly so that we can work out and understand a potential exception.

Thanks!
